---
#------------#
#Installation#
#------------#
- name: Install AGS dependencies
  become: yes
  pacman:
    name:
      - dart-sass
      - jq
    state: present
  tags: [client]

- name: Install aylurs-gtk-shell from AUR
  kewlfft.aur.aur:
    name:
      - aylurs-gtk-shell-git
      - libastal-meta
    use: yay
    state: present
  become: yes
  become_user: aur_builder
  tags: [client]
#-------------#
#Configuration#
#-------------#

