---
- name: Install Nerd Fonts via yay
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    name:
      # - ttf-jetbrains-mono-nerd
      # - ttf-meslo-nerd
      - nerd-fonts-complete
      - noto-fonts-emoji
    state: present
    use: yay
  when: ansible_facts['os_family'] == 'Archlinux'
  tags: [client]
