---
- name: Symlink Hyprlock
  file:
    src: "/home/{{ target_user }}/.dotfiles/roles/hyprlock/files/hyprlock.conf"
    dest: "/home/{{ target_user }}/.config/hypr/hyprlock.conf"
    state: link
    force: yes
  tags: [client]
