---
- name: Install MPD and rmpc (arch)
  package:
    name:
      - mpd
      - mpc # CLI client for controlling MPD
    state: present
  become: yes
  when: ansible_facts['os_family'] == 'Archlinux'
  tags: [client]

- name: Install rmpc from AUR
  kewlfft.aur.aur:
    name: rmpc
    use: yay
    state: present
  become: yes
  become_user: aur_builder
  when: ansible_facts['os_family'] == 'Archlinux'
  tags: [client]

#-----------------------------#
#   create config directory   #
#-----------------------------#

- name: Create MPD config directory
  file:
    path: "/home/{{ target_user | default(ansible_facts['user_id']) }}/.config/mpd"
    state: directory
    owner: "{{ target_user | default(ansible_facts['user_id']) }}"
    mode: '0755'
  become: yes
  tags: [client]

- name: Create MPD playlists directory
  file:
    path: "/home/{{ target_user | default(ansible_facts['user_id']) }}/.config/mpd/playlists"
    state: directory
    owner: "{{ target_user | default(ansible_facts['user_id']) }}"
    mode: '0755'
  become: yes
  tags: [client]

- name: Create rmpc config directory
  file:
    path: "/home/{{ target_user | default(ansible_facts['user_id']) }}/.config/rmpc"
    state: directory
    owner: "{{ target_user | default(ansible_facts['user_id']) }}"
    mode: '0755'
  become: yes
  tags: [client]

#------------------------#
#   Symlinking configs   #
#------------------------#

- name: Symlink MPD config
  file:
    src: "/home/{{ target_user | default(ansible_facts['user_id']) }}/.dotfiles/roles/mpd/files/mpd.conf"
    dest: "/home/{{ target_user | default(ansible_facts['user_id']) }}/.config/mpd/mpd.conf"
    state: link
    force: yes
  become_user: "{{ target_user | default(ansible_facts['user_id']) }}"
  tags: [client]

- name: Symlink rmpc config
  file:
    src: "/home/{{ target_user | default(ansible_facts['user_id']) }}/.dotfiles/roles/mpd/files/rmpc.ron"
    dest: "/home/{{ target_user | default(ansible_facts['user_id']) }}/.config/rmpc/config.ron"
    state: link
    force: yes
  become_user: "{{ target_user | default(ansible_facts['user_id']) }}"
  tags: [client]

#------------------------#
#   Enable MPD service   #
#------------------------#

- name: Enable and start MPD user service
  systemd:
    name: mpd
    scope: user
    enabled: yes
    state: started
  become: no
  become_user: "{{ target_user | default(ansible_facts['user_id']) }}"
  tags: [client]
