# ------------ #
# Installation #
# ------------ #

- name: install SwayNC
  package:
    name: swaync
    state: present
  become: yes
  tags: [client]
  when: ansible_facts['distribution'] == "Archlinux"

# ------------- #
# Configuration #
# ------------- #

- name: create .conf direcotory
  file:
    path: "/home/{{ target_user }}/.config/swaync"
    state: directory
  tags: [client]
  when: ansible_facts['distribution'] == "Archlinux"

- name: symlinc swaync config
  file:
    src: "/home/{{ target_user }}/.dotfiles/swaync/files"
    dest: "/home/{{ target_user }}/.config/swaync"
    state: link
    force: yes
  tags: [client]
  when: ansible_facts['distribution'] == "Archlinux"
