---
- name: install feishin
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    name: feishin
    use: yay
    state: present
  when: ansible_facts['os_family'] == 'Archlinux'
  tags: [client]
